@startuml
'https://plantuml.com/activity-diagram-beta

(*)-->用户登录
-->图书管理界面

-->===B1===
-->进入添加图书界面
-->"输入图书信息，点击添加"
-->===B2===

===B1===-->"进入图书修改界面"
-->"输入图书信息，点击修改"
-->===B2===

===B1===-->"删除图书"
-->===B2===

===B1===-->"搜索图书"
-->if 图书是否存在 then
  -->[true]展示图书
  -->===B2===
else
  -->[false]"提示，并展示所有图书"
  -->===B2===
endif

===B1===-->(*)

===B2===-->图书管理界面
@enduml
